
CREATE TABLE items (
id BIGSERIAL NOT NULL PRIMARY KEY,
name VARCHAR(50) NOT NULL,
price FLOAT NOT NULL,
category VARCHAR(50) NOT NULL
);

CREATE TABLE ticket (
id BIGSERIAL NOT NULL PRIMARY KEY,
customer VARCHAR(50) NOT NULL,
type VARCHAR(10) NOT NULL,
address VARCHAR(50),
day DATE,
time VARCHAR(20),
items TEXT[] NOT NULL
);

INSERT INTO items (name, price, category) VALUES ('Water', 2.15, 'Drinks'),
('Kids Drink', 0.99, 'Drinks'),
('Coffee', 1.49, 'Drinks'),
('Fountain Drink', 2.25, 'Drinks'),
('2 Liter', 4.49, 'Drinks'),
('Cinnamon Stix', 4.49, 'Desserts'),
('Fruit Pizza', 6.49, 'Desserts'),
('Chocolate Pizza', 5.49, 'Desserts'),
('Smores Pizza', 5.49, 'Desserts'),
('Apple Bites', 4.99, 'Desserts'),
('Loaded Sweet Potato Fries', 6.49, 'Desserts'),
('Brownies', 1.49, 'Desserts'),
('Banana Pudding', 3.99, 'Desserts'),
('Bread Pudding', 3.99, 'Desserts'),
('Kids Grilled Cheese', 5.99, 'Kids Menu'),
('Kids Nachos', 4.99, 'Kids Menu'),
('Kids Chicken Nuggets', 5.99, 'Kids Menu'),
('Kids Spaghetti', 5.99, 'Kids Menu'),
('Kids Mac & Cheese', 3.99, 'Kids Menu'),
('Kids Cheese Pizza', 5.49, 'Kids Menu'),
('Lasagna', 8.49, 'Pasta'),
('Chicken Alfredo', 8.49, 'Pasta'),
('Rotel Chicken Spaghetti', 8.49, 'Pasta'),
('Spaghetti & Meat Sauce', 8.49, 'Pasta'),
('Spaghetti & Meatballs', 9.99, 'Pasta'),
('Chicken Parmesan', 8.99, 'Pasta'),
('Family Pasta', 27.99, 'Pasta'),
('Philly Cheese Steak', 6.99, 'Hoagies, Subs, Wraps, and Burgers'),
('Philly Chicken Steak', 6.99, 'Hoagies, Subs, Wraps, and Burgers'),
('Italian Sub', 6.99, 'Hoagies, Subs, Wraps, and Burgers'),
('Meatball Sub', 6.99, 'Hoagies, Subs, Wraps, and Burgers'),
('Pizza Sub', 5.99, 'Hoagies, Subs, Wraps, and Burgers'),
('Chicken Bacon Ranch Hoagie', 6.99, 'Hoagies, Subs, Wraps, and Burgers'),
('Grilled Buffalo Chicken Hoagie', 6.99, 'Hoagies, Subs, Wraps, and Burgers'),
('Ham & Cheese Hoagie', 6.99, 'Hoagies, Subs, Wraps, and Burgers'),
('Chicken Salad Wrap', 6.99, 'Hoagies, Subs, Wraps, and Burgers'),
('Burger', 6.49, 'Hoagies, Subs, Wraps, and Burgers'),
('Cheeseburger', 6.99, 'Hoagies, Subs, Wraps, and Burgers'),
('Italian Wedgie', 7.49, 'Wedgies'),
('Porky Wedgie', 7.49, 'Wedgies'),
('Gregs Cheese Wedgie', 5.99, 'Wedgies'),
('Veggie Wedgie', 6.49, 'Wedgies'),
('Valley Greek Wedgie', 7.49, 'Wedgies'),
('Large Cal-zoli', 8.49, 'Cal-zoli'),
('Regular Cal-zoli', 6.49, 'Cal-zoli'),
('Boneless Wings', 8.99, 'Appetizers'),
('Bone-In Wings', 8.99, 'Appetizers'),
('Beef Nachos', 8.99, 'Appetizers'),
('Chicken Nachos', 9.49, 'Appetizers'),
('BBQ Pork Nachos', 9.49, 'Appetizers'),
('Rotel Cheese Dip & Chips', 3.99, 'Appetizers'),
('Philly Chicken Fries', 7.24, 'Appetizers'),
('Philly Steak Fries', 7.24, 'Appetizers'),
('Rotel Cheese Fries', 6.99, 'Appetizers'),
('BBQ Fries', 7.24, 'Appetizers'),
('Cheesestix', 5.99, 'Appetizers'),
('Hometown Rolls', 6.49, 'Appetizers'),
('Breadsticks With Alfredo', 5.99, 'Appetizers'),
('Side Salad', 3.99, 'Appetizers'),
('Hometown Favorite Pizza', 7.49, 'Pizzas'),
('All Meat Pizza', 7.49, 'Pizzas'),
('Supreme Pizza', 7.49, 'Pizzas'),
('Veggie Pizza', 7.49, 'Pizzas'),
('Philly Cheese Steak Pizza', 7.49, 'Pizzas'),
('Philly Chicken Steak Pizza', 7.49, 'Pizzas'),
('Chicken Parmesan Pizza', 7.49, 'Pizzas'),
('Specialty Cheese Pizza', 7.49, 'Pizzas'),
('Cheeseburger Pizza', 7.49, 'Pizzas'),
('BBQ Pork Pizza', 7.49, 'Pizzas'),
('BBQ Bacon Chicken Pizza', 7.49, 'Pizzas'),
('Chicken Bacon Ranch Pizza', 7.49, 'Pizzas'),
('Hawaiian Pizza', 7.49, 'Pizzas'),
('Spicy Buffalo Chicken Pizza', 7.49, 'Pizzas'),
('Chicken Alfredo Pizza', 7.49, 'Pizzas'),
('Mac & Cheese Pizza', 7.49, 'Pizzas'),
('Create Your Own Pizza', 5.49, 'Pizzas'),
('Weeb Pizza', 8.99, 'Secret Menu'),
('Mayo Sweet Pea Pizza', 5.99, 'Secret Menu'),
('Skateboard Pizza', 12.99, 'Secret Menu'),
('Suicide Soda', 24.99, 'Secret Menu'),
('None Pizza with Left Beef', 69.99, 'Secret Menu'),
('Special Pizza', 4.20, 'Secret Menu'),
('Boneless Pizza', 10.99, 'Secret Menu'),
('Just an Oyster', 99.99, 'Secret Menu'),
('Coders Pizza', 12.99, 'Secret Menu'),
('Pistachio on Pistachio', 0.99, 'Secret Menu'),
('Bone-In Pizza', 16.99, 'Secret Menu'),
('Anchovie-Crusted Pizza', 1.99, 'Secret Menu'),
('Ryan', 0.99, 'Secret Menu'),
('Lettuce Sausage Duck Pizza', 69.99, 'Secret Menu'),
('Belle Delphine Bath Water', 29.99, 'Secret Menu');